In [8]:
import pandas as pd

jantung_df = pd.read_csv('cppt_jantung_extract.csv')
remed_df  = pd.read_csv('resume_medis_extract.csv')

jantung_df = jantung_df.rename(columns={'diagnosaDokter[0].keterangan': 'diagnosa'})
remed_df = remed_df.rename(columns={'diagnosaDokter[0].ketDiagnosaDok':'diagnosa'})

df = (pd.concat([jantung_df, remed_df], ignore_index=True, sort=False).drop_duplicates(subset=['_id']))

df.head()

,Unnamed: 0,_id,diagnosa,grouped_diagnosa,icd10_label,icd9_label
0,0,6773764fbafdbc92fc0184ac,APS CCS II,Angina Pectoris,I25.1 - Atherosclerotic heart disease,NaN
1,1,6773738ce9c3ab55250ace3e,APS CCS II (TMT positif),Angina Pectoris,I25.1 - Atherosclerotic heart disease,NaN
2,2,677372616fcbf619da05ae81,HHD,Hypertensive Heart Disease,NaN,NaN
3,3,6773722d2803009eef037647,CHF,Chronic Heart Failure,Z09.8 - Follow-up examination after other trea...,NaN
4,4,677371ee90c5b094120dc1ac,hhd,Hypertensive Heart Disease,NaN,NaN

In [9]:
df = df.drop_duplicates(subset=['grouped_diagnosa', 'icd10_label'], keep='first')

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2334 entries, 0 to 21190
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        2334 non-null   int64
 1   _id               2334 non-null   object
 2   diagnosa          2334 non-null   object
 3   grouped_diagnosa  2334 non-null   object
 4   icd10_label       2225 non-null   object
 5   icd9_label        1620 non-null   object
dtypes: int64(1), object(5)
memory usage: 127.6+ KB

In [10]:
df_sorted = df.sort_values(by='grouped_diagnosa')
df_sorted.head()

,Unnamed: 0,_id,diagnosa,grouped_diagnosa,icd10_label,icd9_label
17767,8700,66dc3ef0ea39b22abc0525e7,RRD OS,Ablasio retina regmatogenosa,H33.5 -- Other retinal detachments,"90.59--Microscopic examination of blood, Other..."
12876,2189,65f11246aff1d5e12904d27e,RRD OS,Ablasio retina regmatogenosa,H33.0--Retinal detachment with retinal break,14.74--Other mechanical vitrectomy
15239,5337,665d33d2ebe6340ac70d7833,RRD OS,Ablasio retina regmatogenosa,H33.0 -- Retinal detachment with retinal break,14.74 -- Other mechanical vitrectomy
2281,2619,672ac01ab045f68f54023248,Dispnoe ec ADHF,Acute Decompensated Heart Failure,NaN,NaN
449,520,6764b96e87d492eb69057830,ADHF,Acute Decompensated Heart Failure,Z09.8 - Follow-up examination after other trea...,NaN

In [11]:
df_sorted.to_csv('diagnosa_unique_list.csv')